import type { Metadata } from "next";
import { Ubuntu as FontSans } from "next/font/google";
import "./globals.css";
import Navbar from "@/template/navbar";
import Footer from "@/template/footer";
import { cn } from "@/lib/utils";
import Menu from "@/template/menu";

/* const ubuntu = Ubuntu({
	subsets: ["latin"],
	weight: ["300", "700"],
	variable: "--font-ubuntu",
});
 */

const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["300", "700"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <Menu />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
